// 
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// 

using System.Reflection;

[assembly: AssemblyVersion("3.5.31.1822")]
[assembly: AssemblyFileVersion("3.5.31.1822")]
